### PR TITLE
Disallow semicolons forever and ever

### PR DESCRIPTION
**Pull request by vibegui**
A first step to approach [StandardJS](https://github.com/feross/eslint-config-standard). What does @vtex/developers think?

I personally see the community is leaning _heavily_ towards removing semi's lately. Personally, this makes sense to me since they 99.99% of the time don't add _any_ meaning - only noise. The other 0.01%, your script simply won't transpile if a semi is needed, so no worries there.

### CODE REVIEW

**Comment by klzns** [comment]
I, personally, find it weird, but, reactjs org (Redux, react-router) is using it. On the other hand, Facebook and Babel is not. I'm conflicted.

Aesthetically, I think with ; looks nicer. Also it's easier to read. It's like reading a sentence with well defined ponctuation. You now the rhythm.

@tamorim @leandrooriente @gugiserman @gkozlowaski what do you think?

**Comment by klzns** [comment]
Also, I don't like StandardJS, I prefer [XO](https://github.com/sindresorhus/xo)

**Comment by tamorim** [comment]
Well, thinking about the open sourced apps, I think it's better to have code with the semicolons on.

The developers who will use and fork (at least our initial target) our apps probably doesnt know how ASI works and may find it weird, think that's wrong or try do edit following the pattern and hit a pitfall.

There's the case for consistency too, I find it weird to write without semicolons but then HAVE to use one or two here or there because the ASI doesnt cover that case... 

With all that being said, talking personally, I prefer to write without semicolons. I think that reduces noise and aesthetically it's nicer to look at.  

BUT, thinking about the example and footprint we have to leave for other developers, I think we should use semicolons :)

**Comment by vibegui** [comment]
I also prefer it aesthetically. 
One data point: I **never** had to use a semicolon because it was required.

http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding

<3

**Comment by koz** [comment]
I like the idea, and agree that the code is aesthetically better without semicolons. I also agree with @brenoc that with ';' is easier to read, but I think that's a question of habit.
My only concern is with other developers like @tamorim said. But if the community goes with removing, that will not be a problem in the future.

**Comment by gugiserman** [comment]
I already removed semi's from App Store, My Apps, Workspaces and A/B Test

Edit: I mean, I never added them from start

**Comment by klzns** [comment]
@nevescode @resendefreitas halp!

**Comment by nevescode** [comment]
@firstdoit: Nice blog post. 
@brenoc: This conversation is nice but I want to focus on other fronts now. 
btw, I support removing semicolons!

**Comment by vibegui** [comment]
@brenoc what do you say we prepare a new major including this? There are a couple of other rules i'd like to add (mostly things from standard jsx that helps us be more strict) and then projects can opt-in.

**Comment by klzns** [comment]
@firstdoit OK, open a new PR for the other rules, please :)

**Comment by vibegui** [comment]
Will do!

2016-05-24 18:30 GMT+02:00 Breno Calazans notifications@github.com:

> @firstdoit https://github.com/firstdoit OK, open a new PR for the other
> rules, please :)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/vtex/eslint-config-vtex/pull/1#issuecomment-221328073

## 

Guilherme Rodrigues - VTEX Lab

**Pull request merged**
